version: '3.5'

services:
  storage:
    image: redis
    container_name: library-storage
    networks:
      - library
  counter:
    build: ./counter
    container_name: library-counter
    command: npm run start
    restart: unless-stopped
    ports:
      - '3003:3003'
    environment:
      - PORT=3003
      - REDIS_URL=storage
    depends_on:
      - storage
    networks:
      - library

  api:
    build: ./api
    container_name: library-api
    command: npm run start
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - API_HOST=http://library.okitoki.ru/api
      - COUNTER_HOST=http://library.okitoki.ru
    depends_on:
      - counter
    volumes:
      - /home/ilya/projects/library.okitoki.ru/uploads:/app/uploads
    networks:
      - library

  nginx:
    image: nginx:stable-alpine
    container_name: library-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
    networks:
      - library

networks:
  library:
    driver: bridge
