version: '3.5'

services:
  api:
    environment:
      - API_HOST=http://localhost:3000/api
      - COUNTER_HOST=http://172.19.0.3:3002
    volumes:
      - ./api/uploads:/app/uploads
    # extra_hosts:
    #   - 'host.docker.internal:127.0.0.1'
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
